#:schema node_modules/wrangler/config-schema.json
name = "binance-mcp-community"
main = "dist/worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

[placement]
mode = "smart"

[observability]
enabled = true

[[routes]]
pattern = "binance-mcp-community.node2flow.net"
custom_domain = true
